-- RBAC: UserRole → Role (KITCHEN→CHEF, CASHIER→WAITER)
CREATE TYPE "Role" AS ENUM ('OWNER', 'MANAGER', 'WAITER', 'CHEF');

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role" USING (
  CASE "role"::text
    WHEN 'KITCHEN' THEN 'CHEF'::"Role"
    WHEN 'CASHIER' THEN 'WAITER'::"Role"
    ELSE "role"::text::"Role"
  END
);

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'WAITER';

DROP TYPE "UserRole";
